### ISSUE TITLE
Issue #1 - gulp command - TypeError: Cannot set property 'content' of undefined

### ISSUE THREAD

**Issue by ehsanh06** [ehsanh06/statgen#1]
When creating test pages, stumbled across issue upon running gulp or, gulp site-build.

**Output: **
```
[C:\Users\unknown\Documents\Dev\Projects\On-going\statgen>gulp
[16:23:03] Using gulpfile ~\Documents\Dev\Projects\On-going\statgen\gulpfile.js
[16:23:03] Starting 'clean'...
[16:23:03] Finished 'clean' after 3.37 ms
[16:23:03] Starting 'site-build'...
Statgen: Build
[16:23:03] 'site-build' errored after 12 ms
[16:23:03] TypeError: Cannot set property 'content' of undefined
    at C:\Users\unknown\Documents\Dev\Projects\On-going\statgen\tasks\site-build.js:103:30
    at Array.forEach (native)
    at readMD (C:\Users\unknown\Documents\Dev\Projects\On-going\statgen\tasks\site-build.js:90:41)
    at Gulp.<anonymous> (C:\Users\unknown\Documents\Dev\Projects\On-going\statgen\tasks\site-build.js:41:5)
    at module.exports (C:\Users\unknown\Documents\Dev\Projects\On-going\statgen\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\unknown\Documents\Dev\Projects\On-going\statgen\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\unknown\Documents\Dev\Projects\On-going\statgen\node_modules\orchestrator\index.js:214:10)
    at C:\Users\unknown\Documents\Dev\Projects\On-going\statgen\node_modules\orchestrator\index.js:279:18
    at finish (C:\Users\unknown\Documents\Dev\Projects\On-going\statgen\node_modules\orchestrator\lib\runTask.js:21:8)
    at module.exports (C:\Users\unknown\Documents\Dev\Projects\On-going\statgen\node_modules\orchestrator\lib\runTask.js:60:3)

C:\Users\unknown\Documents\Dev\Projects\On-going\statgen>gulp site-build
[16:23:14] Using gulpfile ~\Documents\Dev\Projects\On-going\statgen\gulpfile.js
[16:23:14] Starting 'site-build'...
Statgen: Build
[16:23:14] 'site-build' errored after 13 ms
[16:23:14] TypeError: Cannot set property 'content' of undefined
    at C:\Users\unknown\Documents\Dev\Projects\On-going\statgen\tasks\site-build.js:103:30
    at Array.forEach (native)
    at readMD (C:\Users\unknown\Documents\Dev\Projects\On-going\statgen\tasks\site-build.js:90:41)
    at Gulp.<anonymous> (C:\Users\unknown\Documents\Dev\Projects\On-going\statgen\tasks\site-build.js:41:5)
    at module.exports (C:\Users\unknown\Documents\Dev\Projects\On-going\statgen\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\unknown\Documents\Dev\Projects\On-going\statgen\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\unknown\Documents\Dev\Projects\On-going\statgen\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\Users\unknown\Documents\Dev\Projects\On-going\statgen\node_modules\orchestrator\index.js:134:8)
    at C:\Users\unknown\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^3.7.0\index.js:46:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)

C:\Users\unknown\Documents\Dev\Projects\On-going\statgen>](url)
```

Need to look into this - opening new Branch/PL to investigate this problem

**Comment by ehsanh06** [comment]
Opened PL under branch **undefined-prop-content**

**Comment by ehsanh06** [comment]
Fixed:
```

                var page = [];
                page[0] = data.attr;
                
                // page.content is marked to the DOM Body Object
                page[1] = page.content = marked(data.body);
```
